import { MedicalHistory } from './MedicalHistory';

export const MEDICALRECORDS: MedicalHistory[]=[
    {ref:"001",type:"collection",chronicDisease:"sugar",medicalRecord:[{date:new Date(),disease:"cough",doctor:{id:1,imageUrl:"",name:"Dr.rafeek",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"pain",doctor:{id:2,imageUrl:"",name:"Dr.Sruthy",amount:"10",ratings:3.5,specialization:"gastrology",yearsOfExperience:4,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"sneeze",doctor:{id:3,imageUrl:"",name:"Dr.Maya",amount:"10",ratings:3,specialization:"general",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"cough",doctor:{id:4,imageUrl:"",name:"Dr.Karthi",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"}]}],patient:"Shamra"},
    {ref:"005",type:"single",chronicDisease:"fever",medicalRecord:[{date:new Date(),disease:"cough",doctor:{id:1,imageUrl:"",name:"Dr.Anjali",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"prescription"}]}],patient:"Laxmi"},
    {ref:"002",type:"collection",chronicDisease:"diabetic",medicalRecord:[{date:new Date(),disease:"cough",doctor:{id:1,imageUrl:"",name:"Dr.rafeek",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"pain",doctor:{id:2,imageUrl:"",name:"Dr.Sruthy",amount:"10",ratings:3.5,specialization:"gastrology",yearsOfExperience:4,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"sneeze",doctor:{id:3,imageUrl:"",name:"Dr.Maya",amount:"10",ratings:3,specialization:"general",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"cough",doctor:{id:4,imageUrl:"",name:"Dr.Karthi",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]}],patient:"Maya"},
    {ref:"003",type:"collection",chronicDisease:"cancer",medicalRecord:[{date:new Date(),disease:"cough",doctor:{id:1,imageUrl:"",name:"Dr.rafeek",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"pain",doctor:{id:2,imageUrl:"",name:"Dr.Sruthy",amount:"10",ratings:3.5,specialization:"gastrology",yearsOfExperience:4,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"sneeze",doctor:{id:3,imageUrl:"",name:"Dr.Maya",amount:"10",ratings:3,specialization:"general",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"cough",doctor:{id:4,imageUrl:"",name:"Dr.Karthi",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]}],patient:"Vineetha"},
    {ref:"004",type:"single",chronicDisease:"skin",medicalRecord:[{date:new Date(),disease:"cough",doctor:{id:1,imageUrl:"",name:"Dr.Sooraj",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"prescription"},{url:"",type:"report"}]}],patient:"Sanjeev"},
    {ref:"006",type:"single",chronicDisease:"cough",medicalRecord:[{date:new Date(),disease:"cough",doctor:{id:1,imageUrl:"",name:"Dr.Ruhail",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"prescription"},{url:"",type:"report"}]}],patient:"Arun"},
    {ref:"007",type:"collection",chronicDisease:"cardiac",medicalRecord:[{date:new Date(),disease:"cough",doctor:{id:1,imageUrl:"",name:"Dr.rafeek",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"pain",doctor:{id:2,imageUrl:"",name:"Dr.Sruthy",amount:"10",ratings:3.5,specialization:"gastrology",yearsOfExperience:4,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"sneeze",doctor:{id:3,imageUrl:"",name:"Dr.Maya",amount:"10",ratings:3,specialization:"general",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"},{url:"",type:"prescription"}]},{date:new Date(),disease:"cough",doctor:{id:4,imageUrl:"",name:"Dr.Karthi",amount:"10",ratings:3,specialization:"cardiac",yearsOfExperience:3,lat:0,lon:0,distance:10},dateBooked:new Date(),dateReportReview:new Date(),attachments:[{url:"",type:"report"}]}],patient:"Jamshi"},


];